# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tx_people.fields
import tx_people.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tx_people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompensationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(b'FT', b'Full Time'), (b'PT', b'Part Time')], max_length=250)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', tx_people.fields.ReducedDateField(max_length=10, validators=[tx_people.utils.ReducedDateValidator(), tx_people.utils.ReducedDateValidator(), tx_people.utils.ReducedDateValidator(), tx_people.utils.ReducedDateValidator(), tx_people.utils.ReducedDateValidator(), tx_people.utils.ReducedDateValidator(), tx_people.utils.ReducedDateValidator()])),
                ('end_date', tx_people.fields.ReducedDateField(max_length=10, validators=[tx_people.utils.ReducedDateValidator(), tx_people.utils.ReducedDateValidator(), tx_people.utils.ReducedDateValidator(), tx_people.utils.ReducedDateValidator(), tx_people.utils.ReducedDateValidator(), tx_people.utils.ReducedDateValidator(), tx_people.utils.ReducedDateValidator()])),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('hire_date', tx_people.fields.ReducedDateField(max_length=10, validators=[tx_people.utils.ReducedDateValidator(), tx_people.utils.ReducedDateValidator(), tx_people.utils.ReducedDateValidator()])),
                ('tenure', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('slug', models.SlugField(blank=True, default=None, max_length=255, null=True)),
                ('compensation', models.DecimalField(db_index=True, decimal_places=4, max_digits=12)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('compensation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tx_salaries.CompensationType')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tx_people.Membership')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution', models.TextField(null=True)),
                ('highest_paid', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('median_paid', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('lowest_paid', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('total_number', models.PositiveIntegerField(default=0)),
                ('races', models.TextField()),
                ('female', models.TextField()),
                ('male', models.TextField()),
                ('time_employed', models.TextField()),
                ('date_provided', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, default=None, max_length=255, null=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='tx_people.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PositionStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution', models.TextField(null=True)),
                ('highest_paid', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('median_paid', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('lowest_paid', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('total_number', models.PositiveIntegerField(default=0)),
                ('races', models.TextField()),
                ('female', models.TextField()),
                ('male', models.TextField()),
                ('time_employed', models.TextField()),
                ('date_provided', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, default=None, max_length=255, null=True)),
                ('position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='tx_people.Post')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='tx_salaries.EmployeeTitle'),
        ),
    ]
