# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 17:52
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tx_salaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationstats',
            name='distribution',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='organizationstats',
            name='female',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='organizationstats',
            name='male',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='organizationstats',
            name='races',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='organizationstats',
            name='time_employed',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='positionstats',
            name='distribution',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='positionstats',
            name='female',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='positionstats',
            name='male',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='positionstats',
            name='races',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='positionstats',
            name='time_employed',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
