# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import tx_people.fields
import tx_people.utils


class Migration(migrations.Migration):

    dependencies = [
        ('tx_salaries', '0003_auto_20160329_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='compensation',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tenure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='organizationstats',
            name='highest_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='organizationstats',
            name='lowest_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='organizationstats',
            name='median_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='positionstats',
            name='highest_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='positionstats',
            name='lowest_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='positionstats',
            name='median_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
