# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-30 17:01
from __future__ import unicode_literals

from django.db import migrations
import tx_people.fields
import tx_people.utils


class Migration(migrations.Migration):

    dependencies = [
        ('tx_salaries', '0004_auto_20160329_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='end_date',
            field=tx_people.fields.ReducedDateField(max_length=10, validators=[tx_people.utils.ReducedDateValidator(), tx_people.utils.ReducedDateValidator(), tx_people.utils.ReducedDateValidator(), tx_people.utils.ReducedDateValidator(), tx_people.utils.ReducedDateValidator()]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=tx_people.fields.ReducedDateField(max_length=10, validators=[tx_people.utils.ReducedDateValidator(), tx_people.utils.ReducedDateValidator(), tx_people.utils.ReducedDateValidator()]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=tx_people.fields.ReducedDateField(max_length=10, validators=[tx_people.utils.ReducedDateValidator(), tx_people.utils.ReducedDateValidator(), tx_people.utils.ReducedDateValidator(), tx_people.utils.ReducedDateValidator(), tx_people.utils.ReducedDateValidator()]),
        ),
    ]
